/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PatEtherWallet } from "./PatEtherWallet";
export * as factories from "./factories";
export { PatEtherWallet__factory } from "./factories/PatEtherWallet__factory";
